"use client"
import { FC } from 'react';
import Head from 'next/head';
import Header from '../public/Components/Header';
import Pricing from '../public/Components/Pricing';
import Features from '../public/Components/Features';

const Home: FC = () => {
    return (
        <>
            <Head>
                <title>Pricing UI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header />
                <Pricing />
                <Features />
            </main>
        </>
    )
};

export default Home;